/*
 * Web Server
 *
 * A simple web server for managing users
 *
 * API version: 1.0
 * Contact: dmanor@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/danmanor/WebServerProject/go-server/go"
)

func main() {
	log.Printf("Server started in port 3000")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":3000", router))
}
